<?xml version="1.0"?>
<robot name="kmr"
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Based of https://github.com/stoic-roboticist/kmriiwa_ros_stack -->


  <xacro:include filename="$(find kmr_description)/urdf/iiwa14/materials.xacro" />
  <xacro:include filename="$(find kmr_description)/urdf/iiwa14/iiwa14.xacro"/>
  <xacro:include filename="$(find kmr_description)/urdf/kmp200/kmp200.xacro"/>
  <xacro:include filename="$(find kmr_description)/urdf/d435/_d435.xacro"/>
  <xacro:include filename="$(find kmr_description)/urdf/adapters/camera_adapter.xacro"/>
  <xacro:include filename="$(find kmr_description)/urdf/gripper/robotiq_gripper.xacro"/>
  <xacro:include filename="$(find kmr_description)/urdf/adapters/gripper_adapter.xacro"/>

  <xacro:property name="arm_base_flange_x_pos" value="0.363" />
  <xacro:property name="arm_base_flange_y_pos" value="-0.184" />
  <xacro:property name="arm_base_flange_z_pos" value="-0.01" />
  <xacro:property name="arm_base_flange_yew" value="-1.5708" />
  <xacro:property name="riser_flange_height" value="0.0" />
  <xacro:property name="riser_flange_radius" value="0.121" />
  <xacro:property name="flange_origin_xyz" value="${arm_base_flange_x_pos} ${arm_base_flange_y_pos} ${arm_base_flange_z_pos+riser_flange_height/2}"/>
  <xacro:property name="flange_origin_rpy" value="0 0 ${arm_base_flange_yew}"/>
  <xacro:property name="M_PI" value="3.1415926535897931" />

  <xacro:arg name="robot_name" default="kmr"/>
  <xacro:arg name="hardware_interface" default="PositionJointInterface"/>
  <xacro:arg name="robot_extras" default="$(find kmr_description)/urdf/robot/empty.xacro" />
  <xacro:arg name="gripper" default="$(find kmr_description)/urdf/gripper/robotiq_gripper.xacro" />


  <!--kmp200-->
  <xacro:kmp200 robot_name="$(arg robot_name)" with_wheels="false"/>


  <!--riser flange-->
  <joint name="$(arg robot_name)_base_top_riser_flange_joint" type="fixed">
    <parent link="$(arg robot_name)_base_top_link"/>
    <child link="$(arg robot_name)_riser_flange_link"/>
    <origin xyz="${flange_origin_xyz}" rpy="${flange_origin_rpy}"/>
  </joint>

  <link name="$(arg robot_name)_riser_flange_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder length="${riser_flange_height}" radius="${riser_flange_radius}" />
      </geometry>
      <material name="White"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder length="${riser_flange_height}" radius="${riser_flange_radius}" />
      </geometry>
    </collision>
  </link>


  <!--iiwa-->
  <xacro:iiwa14 hardware_interface="$(arg hardware_interface)" robot_name="$(arg robot_name)" parent="$(arg robot_name)_riser_flange_link">
    <origin xyz="0 0 ${riser_flange_height/2}" rpy="0 0 0" />
  </xacro:iiwa14>


  <!-- Gripper with adapter -->
  <xacro:gripper_adapter parent="$(arg robot_name)_link_ee" />

  <xacro:gripper parent="gripper_adapter">
    <origin xyz="0 0 0.005" rpy="0 0 0" />
  </xacro:gripper>


  <!-- Cameras with adapters -->
  <!-- These values has to be tuned to match the pysical robot -->
  <xacro:camera_adapter parent="$(arg robot_name)_base_top_link" camera_position="left">
    <origin xyz="0 0.275 0" rpy="0 0 0"/>
  </xacro:camera_adapter>

  <xacro:camera_adapter parent="$(arg robot_name)_base_top_link" camera_position="right">
    <origin xyz="0 -0.275 0" rpy="0 0 0"/>
  </xacro:camera_adapter>

  <xacro:sensor_d435 parent="left_camera_adapter" name="camera_left" use_nominal_extrinsics="false">
    <origin xyz="0 0 0.005" rpy="0 0 ${M_PI/2}" />
  </xacro:sensor_d435>

  <xacro:sensor_d435 parent="right_camera_adapter" name="camera_right" use_nominal_extrinsics="false">
    <origin xyz="0 0 0.005" rpy="0 0 ${-M_PI/2}" />
  </xacro:sensor_d435>

  <xacro:sensor_d435 parent="$(arg robot_name)_base_top_link" name="camera_front" use_nominal_extrinsics="false">
    <origin xyz="0.5 0 -0.0075" rpy="0 0 0" />
  </xacro:sensor_d435>

  <xacro:sensor_d435 parent="gripper_adapter" name="camera_manipulator" use_nominal_extrinsics="false">
    <origin xyz="0 0.035 0" rpy="0 ${-M_PI/2} ${-M_PI/2}" />
  </xacro:sensor_d435>


</robot>
