# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - iiwa_hand_controller

  iiwa_hand_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - kmr_joint_1
      - kmr_joint_2
      - kmr_joint_3
      - kmr_joint_4
      - kmr_joint_5
      - kmr_joint_6
      - kmr_joint_7