# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    iiwa_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

iiwa_hand_controller:
  ros__parameters:
    joints:
      - kmr_joint_1
      - kmr_joint_2
      - kmr_joint_3
      - kmr_joint_4
      - kmr_joint_5
      - kmr_joint_6
      - kmr_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity